define([], function() {
  return {
    "PropertyPaneDescription": "Dynamic form settings",
    "BasicGroupName": "Basic",
    "DescriptionFieldLabel": "Description",
    "PropertyGroupBasic": "Basic settings",
    "PropertyGroupButtons": "Button settings",
    "PropertyGroupConfigIO": "Config import/export",
    "PropListLabel": "SharePoint list",
    "PropModeLabel": "Form mode",
    "PropModeNew": "New",
    "PropModeEdit": "Edit",
    "PropModeView": "View",
    "PropItemIdQueryParamLabel": "Item ID query parameter",
    "PropLabelPositionLabel": "Label position",
    "PropLabelTop": "Top",
    "PropLabelLeft": "Left",
    "PropShowFieldDescriptionLabel": "Show field description",
    "PropToggleOn": "On",
    "PropToggleOff": "Off",
    "PropSubmitButtonLabel": "Submit button text",
    "PropSubmitButtonPlaceholder": "Submit (default)",
    "PropShowCancelButtonLabel": "Show cancel button",
    "PropCancelButtonLabel": "Cancel button text",
    "PropCancelButtonPlaceholder": "Cancel (default)",
    "PropCancelRedirectUrlLabel": "Redirect URL after cancel",
    "PropCancelRedirectUrlPlaceholder": "Leave empty to reset form",
    "PropSubmitRedirectUrlLabel": "Redirect URL after submit",
    "PropSubmitRedirectUrlPlaceholder": "Leave empty to show success message",
    "PropSubmitSuccessMessageLabel": "Submit success message",
    "PropSubmitSuccessMessagePlaceholder": "Form submitted successfully! (default)",
    "ConfigExportButton": "Export config",
    "ConfigImportButton": "Import config",
    "ConfigImportSuccess": "Configuration imported.",
    "ConfigImportInvalid": "Invalid configuration file.",
    "ConfigImportReadError": "Failed to read configuration file.",
    "ConfigImportWarningList": "List not found. Please reselect the list in settings.",
    "DesignerTitle": "Form Designer",
    "DesignerButton": "Design Form",
    "DesignerBackButton": "Back",
    "CommonSave": "Save",
    "CommonSaving": "Saving...",
    "CommonLoading": "Loading...",
    "CommonRetry": "Retry",
    "CommonContinueEditing": "Continue editing",
    "CommonReadOnly": "Read-only",
    "CommonCancel": "Cancel",
    "CommonSubmit": "Submit",
    "CommonSubmitting": "Submitting...",
    "CommonContinueCreate": "Continue creating",
    "CommonUnknownError": "Unknown error",
    "RuntimeNoSchemaWarning": "Please configure the form in web part properties",
    "LoadErrorNoItemIdFromUrl": "Item ID was not found in URL. Unable to load form data.",
    "LoadConfigFailed": "Failed to load form configuration",
    "SaveFailedDefault": "Save failed, please try again",
    "UploadAttachmentFailedTemplate": "Failed to upload attachment \"{0}\": {1}",
    "FormInvalidMessageDefault": "Invalid format",
    "FormStepValidationError": "Please complete all required fields before continuing",
    "FormSubmitFailedDefault": "Submit failed, please try again",
    "FormSubmitLabelEdit": "Save",
    "FormSubmitSuccessEdit": "Updated successfully!",
    "FormSubmitSuccessNew": "Submitted successfully!",
    "FormStepHiddenTitle": "Current step is hidden",
    "FormStepHiddenDescription": "Please adjust field conditions to make this step visible.",
    "FormUploadingAttachments": "Uploading attachments",
    "FormErrorSummaryTitle": "There are {0} errors in this form:",
    "DialogCancelTitle": "Confirm cancel",
    "DialogCancelSubText": "You have unsaved changes. Discard them?",
    "DialogDiscardChanges": "Discard changes",
    "StepPrev": "Previous",
    "StepNext": "Next",
    "StepEmptyNoVisibleFields": "No visible fields in this step",
    "FieldPlaceholderSelect": "Please select",
    "FieldUrlDescriptionLabel": "Description (optional)",
    "FieldUrlDescriptionPlaceholder": "Display text for the link",
    "FieldRichTextEmpty": "No content",
    "FieldImageReadFileFailed": "Failed to read file content",
    "FieldImageUploadFailed": "Failed to upload image",
    "FieldImageNoImage": "No image",
    "FieldImageRuntimeOnly": "Image picker is available in runtime mode",
    "FieldPersonMissingContext": "Missing SharePoint context",
    "FieldPersonPlaceholder": "Type name or email to search (at least 3 chars)...",
    "FieldAttachmentMissingContext": "Missing SharePoint context",
    "FieldAttachmentNeedListName": "Please configure list name in form settings",
    "FieldAttachmentLoadListFailed": "Unable to load list ID for \"{0}\"",
    "FieldAttachmentLoadingList": "Loading list information...",
    "FieldAttachmentNeedListInfo": "Please configure list name or list ID (GUID) to enable attachments.",
    "FieldAttachmentUploadOnSubmit": "Attachments will be uploaded on submit.",
    "FieldAttachmentAddButton": "Add attachment",
    "FieldAttachmentClear": "Clear",
    "FieldAttachmentRemoveAria": "Remove attachment",
    "FieldAttachmentEmpty": "No attachments selected",
    "FieldTaxonomyMissingContext": "Missing SharePoint context",
    "FieldTaxonomyMissingTermSetId": "Missing Term Set ID (TermSetId)",
    "FieldTaxonomyWorkbenchTitle": "Workbench limitation",
    "FieldTaxonomyWorkbenchDesc": "Taxonomy field is not available in local workbench. Deploy to SharePoint to test.",
    "FieldTaxonomyDeployLink": "Deploy to SharePoint",
    "FieldTaxonomyWorkbenchPlaceholder": "(Available only in real SharePoint environment)",
    "FieldTaxonomyWorkbenchDescription": "This is a placeholder. Deploy to SharePoint for full functionality.",
    "FieldTaxonomyInvalidTermSetId": "Invalid Term Set ID format: {0}",
    "FieldTaxonomyPanelTitle": "Select {0}",
    "FieldTaxonomyPlaceholder": "Select terms...",
    "FieldBooleanYes": "Yes",
    "FieldBooleanNo": "No",
    "DesignerLoadFieldsFailed": "Failed to load fields",
    "DesignerNoListSelected": "No list selected",
    "DesignerStepNotFound": "Step not found",
    "DesignerAttachmentAlreadyExists": "Attachment field already exists",
    "DesignerStepDefaultTitle": "Step {0}",
    "DesignerAddStep": "+ Add step",
    "DesignerDeleteStep": "Delete step",
    "DesignerStepTitlePlaceholder": "Step title",
    "DesignerStepDescriptionPlaceholder": "Step description",
    "DesignerShowStep": "Show this step",
    "DesignerShowStepHelp": "When unchecked, this step is hidden by default and can be shown via other field logic.",
    "DesignerStepLayout": "Step layout",
    "DesignerLayoutStack": "Vertical stack",
    "DesignerLayoutGrid": "Grid layout",
    "DesignerColumns": "Columns",
    "DesignerColumnOption": "{0} columns",
    "DesignerRichTextChip": "Rich text",
    "DesignerColumnBadge": "{0} cols",
    "DesignerDelete": "Delete",
    "DesignerEdit": "Edit",
    "DesignerFieldPickerTitle": "Select a field to add",
    "DesignerFieldTypeAndInternal": "Type: {0} | Internal Name: {1}",
    "DesignerAddFieldTooltip": "Click to add field",
    "DesignerAddFieldHere": "+ Add field here",
    "DesignerClickAddField": "Click below to add fields",
    "DesignerAddFirstField": "+ Add first field",
    "DesignerRequiredFieldTitle": "Required",
    "DesignerPaletteListFields": "List fields",
    "DesignerCustomFields": "Custom fields",
    "DesignerCustomFieldsDesc": "Add fields via buttons on the right (not saved to SharePoint)",
    "DesignerSPFields": "SharePoint fields",
    "DesignerAddableFieldsCount": "Addable fields ({0})",
    "DesignerNoAddableFields": "No more fields available to add",
    "DesignerCustomRichTextTitle": "Rich text editor",
    "DesignerCustomRichTextDesc": "Use for instructions, notes, and rich content",
    "DesignerRichTextPlaceholder": "Enter rich text here...",
    "DesignerFieldTypeLabel": "{0} field",
    "PropertyPanelTitle": "Field properties",
    "PropertyPanelFieldInfo": "Field info",
    "PropertyPanelFieldName": "Name:",
    "PropertyPanelFieldType": "Type:",
    "PropertyPanelFieldInternalName": "Internal name:",
    "PropertyPanelFieldRequired": "Required:",
    "PropertyPanelFieldMaxLength": "Max length:",
    "PropertyPanelFieldChoices": "Choices:",
    "PropertyPanelFieldLookupList": "Lookup list:",
    "PropertyPanelColumnSpan": "Column span",
    "PropertyPanelColumnSpanDesc": "Set the number of columns this field occupies. Effective only in grid layout.",
    "PropertyPanelColumnSpanHint": "Example: In a 3-column layout, setting to 2 makes this field span 2 columns.",
    "PropertyPanelHelpText": "Field help text",
    "PropertyPanelHelpTextDesc": "Shown below the field to guide users.",
    "PropertyPanelHelpTextPlaceholder": "Example: Please enter full department name",
    "PropertyPanelRichTextContent": "Rich text content",
    "PropertyPanelRichTextDesc": "Edit rich text content shown in the form.",
    "PropertyPanelMissingSPField": "SP field info not found. Some settings may not display correctly.",
    "PropertyFieldTypeText": "Single line text",
    "PropertyFieldTypeMultiline": "Multiple lines of text",
    "PropertyFieldTypeNumber": "Number",
    "PropertyFieldTypeDatetime": "Date and time",
    "PropertyFieldTypeDropdown": "Dropdown",
    "PropertyFieldTypeMultiselect": "Multi-select",
    "PropertyFieldTypeLookup": "Lookup",
    "PropertyFieldTypePerson": "Person",
    "PropertyFieldTypeBoolean": "Yes/No",
    "PropertyFieldTypeImage": "Image",
    "PropertyFieldTypeUrl": "Hyperlink",
    "PropertyFieldTypeTaxonomy": "Managed metadata",
    "PropertyFieldTypeAttachment": "Attachment",
    "PropertyFieldTypeRichtext": "Rich text",
    "ConditionOpEq": "equals",
    "ConditionOpNe": "not equals",
    "ConditionOpGt": "greater than",
    "ConditionOpGe": "greater than or equal",
    "ConditionOpLt": "less than",
    "ConditionOpLe": "less than or equal",
    "ConditionOpContains": "contains",
    "ConditionOpStartsWith": "starts with",
    "ConditionVisibilityLabel": "Visibility condition",
    "ConditionVisibilityDesc": "Set when this field is shown. Leave empty to always show.",
    "ConditionNoRules": "No conditions set. Field will always be visible.",
    "ConditionRuleLabel": "Condition {0}",
    "ConditionFieldLabel": "Field",
    "ConditionFieldPlaceholder": "Select field",
    "ConditionOperatorLabel": "Operator",
    "ConditionValueLabel": "Value",
    "ConditionValuePlaceholder": "Enter comparison value",
    "ConditionAnd": "AND",
    "ConditionAdd": "+ Add condition",
    "ConditionHint": "Tip: Conditions are combined with AND. For example: Department equals \"IT\" AND Status not equals \"Closed\".",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});
