define([], function() {
  return {
    "PropertyPaneDescription": "动态表单配置",
    "BasicGroupName": "基本设置",
    "DescriptionFieldLabel": "描述",
    "PropertyGroupBasic": "基本设置",
    "PropertyGroupButtons": "按钮配置",
    "PropListLabel": "SharePoint 列表",
    "PropModeLabel": "表单模式",
    "PropModeNew": "新建",
    "PropModeEdit": "编辑",
    "PropModeView": "查看",
    "PropItemIdQueryParamLabel": "ItemId 参数名",
    "PropLabelPositionLabel": "标签位置",
    "PropLabelTop": "上方",
    "PropLabelLeft": "左侧",
    "PropShowFieldDescriptionLabel": "显示字段描述",
    "PropToggleOn": "显示",
    "PropToggleOff": "隐藏",
    "PropSubmitButtonLabel": "提交按钮文字",
    "PropSubmitButtonPlaceholder": "提交（默认）",
    "PropShowCancelButtonLabel": "显示取消按钮",
    "PropCancelButtonLabel": "取消按钮文字",
    "PropCancelButtonPlaceholder": "取消（默认）",
    "PropCancelRedirectUrlLabel": "取消后跳转URL",
    "PropCancelRedirectUrlPlaceholder": "留空则重置表单",
    "PropSubmitRedirectUrlLabel": "提交后跳转URL",
    "PropSubmitRedirectUrlPlaceholder": "留空则显示成功消息",
    "PropSubmitSuccessMessageLabel": "提交成功消息",
    "PropSubmitSuccessMessagePlaceholder": "表单提交成功！（默认）",
    "DesignerTitle": "表单设计器",
    "DesignerButton": "设计表单",
    "DesignerBackButton": "返回",
    "CommonSave": "保存",
    "CommonSaving": "保存中...",
    "CommonLoading": "加载中...",
    "CommonRetry": "重试",
    "CommonContinueEditing": "继续编辑",
    "CommonReadOnly": "只读",
    "CommonCancel": "取消",
    "CommonSubmit": "提交",
    "CommonSubmitting": "提交中...",
    "CommonContinueCreate": "继续新增",
    "CommonUnknownError": "未知错误",
    "RuntimeNoSchemaWarning": "请在 Web Part 属性中配置表单",
    "LoadErrorNoItemIdFromUrl": "未从 URL 获取到 Item ID，无法加载表单数据。",
    "LoadConfigFailed": "加载表单配置失败",
    "SaveFailedDefault": "保存失败，请重试",
    "UploadAttachmentFailedTemplate": "上传附件 \"{0}\" 失败: {1}",
    "FormInvalidMessageDefault": "格式不正确",
    "FormStepValidationError": "请完成所有必填项后再继续",
    "FormSubmitFailedDefault": "提交失败，请重试",
    "FormSubmitLabelEdit": "保存",
    "FormSubmitSuccessEdit": "更新成功！",
    "FormSubmitSuccessNew": "提交成功！",
    "FormStepHiddenTitle": "当前步骤不可见",
    "FormStepHiddenDescription": "请通过其他字段的配置来控制此步骤的显示",
    "FormUploadingAttachments": "正在上传附件",
    "FormErrorSummaryTitle": "表单还有 {0} 处错误：",
    "DialogCancelTitle": "确认取消",
    "DialogCancelSubText": "当前有未保存的修改，确定要放弃这些更改吗？",
    "DialogDiscardChanges": "放弃修改",
    "StepPrev": "上一步",
    "StepNext": "下一步",
    "StepEmptyNoVisibleFields": "此步骤没有可显示的字段",
    "FieldPlaceholderSelect": "请选择",
    "FieldUrlDescriptionLabel": "描述（可选）",
    "FieldUrlDescriptionPlaceholder": "链接显示的文本",
    "FieldRichTextEmpty": "暂无内容",
    "FieldImageReadFileFailed": "无法读取文件内容",
    "FieldImageUploadFailed": "上传图片失败",
    "FieldImageNoImage": "无图片",
    "FieldImageRuntimeOnly": "图片选择器在运行模式下可用",
    "FieldPersonMissingContext": "缺少 SharePoint Context",
    "FieldPersonPlaceholder": "输入姓名或邮箱搜索（至少3个字符）...",
    "FieldAttachmentMissingContext": "缺少 SharePoint Context",
    "FieldAttachmentNeedListName": "请在表单配置中指定列表名称",
    "FieldAttachmentLoadListFailed": "无法获取列表 \"{0}\" 的 ID",
    "FieldAttachmentLoadingList": "正在加载列表信息...",
    "FieldAttachmentNeedListInfo": "请在表单配置中指定列表名称或列表 ID（GUID）以启用附件功能。",
    "FieldAttachmentUploadOnSubmit": "附件将在提交时统一上传。",
    "FieldAttachmentClear": "清空",
    "FieldAttachmentRemoveAria": "移除附件",
    "FieldAttachmentEmpty": "尚未选择附件",
    "FieldTaxonomyMissingContext": "缺少 SharePoint Context",
    "FieldTaxonomyMissingTermSetId": "缺少术语集 ID (TermSetId)",
    "FieldTaxonomyWorkbenchTitle": "Workbench 环境限制",
    "FieldTaxonomyWorkbenchDesc": "Taxonomy 字段在本地 Workbench 中不可用，需要部署到 SharePoint 才能测试。",
    "FieldTaxonomyDeployLink": "部署到 SharePoint",
    "FieldTaxonomyWorkbenchPlaceholder": "（仅在真实 SharePoint 环境中可用）",
    "FieldTaxonomyWorkbenchDescription": "此为占位符，请部署到 SharePoint 后测试完整功能",
    "FieldTaxonomyInvalidTermSetId": "无效的术语集 ID 格式: {0}",
    "FieldTaxonomyPanelTitle": "选择{0}",
    "FieldTaxonomyPlaceholder": "选择术语...",
    "FieldBooleanYes": "是",
    "FieldBooleanNo": "否",
    "DesignerLoadFieldsFailed": "加载字段失败",
    "DesignerNoListSelected": "未选择列表",
    "DesignerStepNotFound": "未找到步骤",
    "DesignerAttachmentAlreadyExists": "附件字段已存在",
    "DesignerStepDefaultTitle": "步骤 {0}",
    "DesignerAddStep": "+ 添加步骤",
    "DesignerDeleteStep": "删除步骤",
    "DesignerStepTitlePlaceholder": "步骤标题",
    "DesignerStepDescriptionPlaceholder": "步骤描述",
    "DesignerShowStep": "显示此步骤",
    "DesignerShowStepHelp": "取消勾选后，此步骤将默认隐藏，可通过其他字段的配置来控制显示（例如：点击按钮后显示）",
    "DesignerStepLayout": "步骤布局",
    "DesignerLayoutStack": "垂直堆叠",
    "DesignerLayoutGrid": "网格布局",
    "DesignerColumns": "列数",
    "DesignerColumnOption": "{0}列",
    "DesignerRichTextChip": "富文本",
    "DesignerColumnBadge": "{0}列",
    "DesignerDelete": "删除",
    "DesignerEdit": "编辑",
    "DesignerFieldPickerTitle": "选择要添加的字段",
    "DesignerFieldTypeAndInternal": "类型: {0} | 内部名称: {1}",
    "DesignerAddFieldTooltip": "点击添加字段",
    "DesignerAddFieldHere": "+ 在此处添加字段",
    "DesignerClickAddField": "点击下方按钮添加字段",
    "DesignerAddFirstField": "+ 添加第一个字段",
    "DesignerRequiredFieldTitle": "必填",
    "DesignerPaletteListFields": "列表字段",
    "DesignerCustomFields": "自定义字段",
    "DesignerCustomFieldsDesc": "通过右侧按钮添加字段（不保存到 SharePoint）",
    "DesignerSPFields": "SharePoint 字段",
    "DesignerAddableFieldsCount": "可添加字段（{0}）",
    "DesignerNoAddableFields": "已没有可添加的字段",
    "DesignerCustomRichTextTitle": "富文本编辑器",
    "DesignerCustomRichTextDesc": "用于输入说明文字、提示信息等",
    "DesignerRichTextPlaceholder": "在此输入富文本内容...",
    "DesignerFieldTypeLabel": "{0} 字段",
    "PropertyPanelTitle": "字段属性",
    "PropertyPanelFieldInfo": "字段信息",
    "PropertyPanelFieldName": "字段名：",
    "PropertyPanelFieldType": "字段类型：",
    "PropertyPanelFieldInternalName": "内部名称：",
    "PropertyPanelFieldRequired": "必填：",
    "PropertyPanelFieldMaxLength": "最大长度：",
    "PropertyPanelFieldChoices": "选项：",
    "PropertyPanelFieldLookupList": "查找列表：",
    "PropertyPanelColumnSpan": "列跨度",
    "PropertyPanelColumnSpanDesc": "设置字段占据的列数。仅在网格布局下生效。",
    "PropertyPanelColumnSpanHint": "例如：在3列布局中，设置为2则该字段占据2列宽度",
    "PropertyPanelHelpText": "字段提示",
    "PropertyPanelHelpTextDesc": "显示在字段下方的说明文字，可用于示例或填写提示。",
    "PropertyPanelHelpTextPlaceholder": "例如：请输入完整部门名称",
    "PropertyPanelRichTextContent": "富文本内容",
    "PropertyPanelRichTextDesc": "编辑富文本字段的内容，这些内容将在表单中显示。",
    "PropertyPanelMissingSPField": "未找到对应的 SharePoint 字段信息，部分配置可能无法正确显示。",
    "PropertyFieldTypeText": "单行文本",
    "PropertyFieldTypeMultiline": "多行文本",
    "PropertyFieldTypeNumber": "数字",
    "PropertyFieldTypeDatetime": "日期时间",
    "PropertyFieldTypeDropdown": "下拉选择",
    "PropertyFieldTypeMultiselect": "多选",
    "PropertyFieldTypeLookup": "查找",
    "PropertyFieldTypePerson": "人员",
    "PropertyFieldTypeBoolean": "是/否",
    "PropertyFieldTypeImage": "图片",
    "PropertyFieldTypeUrl": "超链接",
    "PropertyFieldTypeTaxonomy": "托管元数据",
    "PropertyFieldTypeAttachment": "附件",
    "PropertyFieldTypeRichtext": "富文本",
    "ConditionOpEq": "等于",
    "ConditionOpNe": "不等于",
    "ConditionOpGt": "大于",
    "ConditionOpGe": "大于或等于",
    "ConditionOpLt": "小于",
    "ConditionOpLe": "小于或等于",
    "ConditionOpContains": "包含",
    "ConditionOpStartsWith": "开始于",
    "ConditionVisibilityLabel": "可见性条件",
    "ConditionVisibilityDesc": "设置字段何时显示。留空则始终显示。",
    "ConditionNoRules": "暂无条件设置，字段将始终显示",
    "ConditionRuleLabel": "条件 {0}",
    "ConditionFieldLabel": "字段",
    "ConditionFieldPlaceholder": "选择字段",
    "ConditionOperatorLabel": "操作符",
    "ConditionValueLabel": "值",
    "ConditionValuePlaceholder": "输入比较的值",
    "ConditionAnd": "且",
    "ConditionAdd": "+ 添加条件",
    "ConditionHint": "提示：所有条件之间是“与”的关系（必须同时满足）。例如：部门等于“IT” 且状态不等于“已关闭”。",
    "AppLocalEnvironmentSharePoint": "应用正在本地环境作为 SharePoint Web Part 运行",
    "AppLocalEnvironmentTeams": "应用正在本地环境作为 Microsoft Teams 应用运行",
    "AppLocalEnvironmentOffice": "应用正在本地环境在 office.com 运行",
    "AppLocalEnvironmentOutlook": "应用正在本地环境在 Outlook 运行",
    "AppSharePointEnvironment": "应用正在 SharePoint 页面运行",
    "AppTeamsTabEnvironment": "应用正在 Microsoft Teams 运行",
    "AppOfficeEnvironment": "应用正在 office.com 运行",
    "AppOutlookEnvironment": "应用正在 Outlook 运行",
    "UnknownEnvironment": "应用正在未知环境运行"
  }
});
